### ISSUE TITLE
Problem with input if input length > 31

### ISSUE THREAD

**Issue by Keruspe** [c-util/c-shquote#1]
When trying to figure out https://github.com/bus1/dbus-broker/issues/172 I ended up finding a really weird bug.

When editing the `src/test-api.c` to test with values other than `"foo"`, putting several paths, I get fully reproductible failures when the path length is above 31. `"/usr/x86_64-pc-linux-gnu/libexe"` succeeds and `"/usr/x86_64-pc-linux-gnu/libexec"` fails.

I don't understand why but in `c_shquote_parse_argv`, the `n_input` variable gets set to 0 at the same time as `n_in` does.

Adding a `size_t foo = n_input;` and replacing the two `n_in = n_input;` with `n_in = foo;` "solves" the issue, but n_input still gets assigned 0.

**Comment by Keruspe** [comment]
After further debugging, the culprit is `*out = '\0'`, will submit a patch shortly

**Comment by teg** [comment]
Thanks for looking into this. Fixed in master.
